# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do |options|
	increment_version_number(version_number: options[:version])
	get_certificates
    	get_provisioning_profile
     	api_key = app_store_connect_api_key(
    	key_id: "N6JAFQ297C",
    	issuer_id: "f8d1c379-27c7-42dc-97ef-e5ccb78c04d6",
    	key_filepath: "./AuthKey_N6JAFQ297C.p8"
  	)

  pilot(api_key: api_key)
 	increment_build_number(xcodeproj: "SeSAC_Motto.xcodeproj")
    	build_app(workspace: "SeSAC_Motto.xcworkspace", scheme: "SeSAC_Motto")
   	upload_to_testflight(
		skip_waiting_for_build_processing: true
		 )

#   	send_slack
	end

  error do |lane, exception, options|
    	slack(
     	message: "에러 발생 : #{exception}",
      	success: false,
	slack_url: "https://hooks.slack.com/services/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"
    	)
	end

lane :send_slack do
    version = get_version_number(
	xcodeproj: "SeSAC_Motto.xcodeproj", 
	target: "SeSAC_Motto"
    )
    build = get_build_number(xcodeproj: "SeSAC_Motto.xcodeproj") 
    
    slack(
      message: "앱스토어 업로드가 완료되었습니다.",
      channel: "#fastlane-테스트",
      slack_url: "https://hooks.slack.com/services/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",
      default_payloads: [:lane, :test_result, :git_branch, :git_author],
      payload: {
	"Version": version + " (" + build + ")"
      }
    )
   end

lane :buildTest do
 build_app(workspace: "SeSAC_Motto.xcworkspace", scheme: "SeSAC_Motto")
   end

after_all do
	send_slack
end


end

    # add actions here: https://docs.fastlane.tools/actions
